FROM python:3.11-alpine

RUN apk update && apk add --no-cache gcc musl-dev

RUN pip install --upgrade pip

WORKDIR /app

COPY bot/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY bot/ .

WORKDIR /app

CMD ["python3", "-u", "main.py"]