services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker


  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./docker/mongo/mongodump:/mongodump
      - ./docker/mongo/data:/data/db
    ports:
      - "${MONGO_PORT}:27017"
    command: mongod --quiet --logpath /dev/null --logappend
    logging:
      driver: "none"
    env_file:
      - .env

